server:
  port: 8080

spring:
  application:
    name: aerztekasse

  devtools:
    remote:
      secret: teste
    add-properties: true

  jackson:
    serialization:
      indent-output: true

  datasource:
    url: jdbc:h2:mem:pizza;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console

  sql:
    init:
      mode: always
      platform: h2

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
